---
#base de données
mediawiki_db_name: "mediawiki"
mediawiki_db_user: "mediawiki"
mediawiki_db_pass: "password"
mediawiki_admin_user: "admin"
mediawiki_admin_pass: "password"
mediawiki_directory: "/var/www/html/{{mediawiki_name}}"
mediawiki_name: "mywiki"
mediawiki_title: "Formation ansible"
mediawiki_db_hosts: "{{web01qual}}"
mediawiki_archive_url: "https://releases.wikimedia.org/mediawiki/1.41/mediawiki-core-1.41.0.tar.gz"
mediawiki_maintenance_directory: 
