---
- name: creation des FS applicatif
  hosts: all
  become: yes
  become_method: sudo
  become_flags: '-'
  vars: 
    AP_CODE: "AP10631"
    AP_NUM_ID: "10631"
    AP_PENTAGRAME: "mbm00"
    delivery_size: 10G
    applis_size: 10G
    logs_size: 10G
  
  tasks:
    - incude_role:
        name: create_fs

