---
- name: creation des FS applicatif
  hosts: all
  become: yes
  vars: 
    AP_CODE: "AP10631"
    AP_NUM_ID: "10631"
    AP_PENTAGRAME: "mbm00"
    delivery_size: 10G
    applis_size: 10G
    logs_size: 3G
  
  roles: 
    - create_fs

