--- 
- name: creation du group web  
  group:
    name: "web"
    state: present 
    gid: '1070' 

- name: ceation utilisateur FIN
  user:
    name: "fin"
    group: "web"

- name: droit sur repertoire
  file:
    path: "{{ item }}"
    owner: "fin"
    group: "web"
    state: directory
    recurse: yes
    mode: "0755"
  loop:
    - "/applis/{{ AP_NUM_ID }}-{{ AP_PENTAGRAME }}"
    - "/applis/logs/{{ AP_NUM_ID }}-{{ AP_PENTAGRAME }}"
    - "/applis/delivery/{{ AP_NUM_ID }}-{{ AP_PENTAGRAME }}"


#########################creation du vg_apps

- name: creation du vg_apps
  parted: 
    device: /dev/sdb
    number: 1
    flags: [ lvm ]
    state: present 
    
- name: creation de VG
  lvg:
    vg: vg_apps
    pvs: /dev/sdb1

#######################creation des différents lv
- name: creation du lv log
  lvol:
    vg: vg_apps
    lv: "lv_dlv_{{ AP_PENTAGRAME }}"
    size: "{{ delivery_size }}"
    force: no
    shrink: no

- name: ceration du FS 
  filesystem:
    fstype: ext4
    dev: "/dev/vg_apps_lv_dlv_{{ AP_PENTAGRAME }}"

- name: montage du volume 
  mount:
    name: "/applis/delivery/{{ AP_NUM_ID }}-{{ AP_PENTAGRAME }}"
    src: "/dev/vg_apps/lv_dlv_{{ AP_PENTAGRAME }}"
    fstype: ext4
    state: mounted


####################creation des fs appli et log 
- name: creation du lv_applis
  lvol:
    vg: vg_apps 
    lv: "lv_{{ AP_PENTAGRAME }}"
    size: "{{ applis_size }}"
    force: no
    shrink: no 

- name: cration du FS 
  filesystem:
    fstype: ext4
    dev: "/dev/vg_apps/lv_{{ AP_PENTAGRAME }}"

- name: montage de volume 
  mount: 
    name: "/applis/{{ AP_NUM_ID }}-{{ AP_PENTAGRAME }}"
    src: "/dev/vg_apps/lv_{{ AP_PENTAGRAME }}"
    fstype: ext4
    opts: default,nodev
    state: mounted

- name: creation du lv_logs
  lvol:
    vg: vg_apps
    lv: "lv_logs_{{ AP_PENTAGRAME }}"
    size: "{{ log_size }}"
    force: no
    shrink: no

- name: cration fs log 
  filesystem:
    fstype: ext4 
    dev: "/dev/vg_apps/lv_logs_{{ AP_PENTAGRAME }}"

- name: montage du volume
  mount: 
    name: "/applis/logs/{{ AP_NUM_ID }}-{{ AP_PENTAGRAME }}"
    src: "/dev/vg_apps/lv_logs_{{ AP_PENTAGRAME }}"
    fstype: ext4
    opts: default,nodev
    dump: "1"
    passno: "2" 
    state: mounted